Initial checkin for test app
jenkins-x-apps/jx-app-test-lifecycle pull request #1
Opened 2019-02-21 13:59 UTC by deanesmith

App used by Jenkins X BDD testing as a stable, predictable app for the sole purpose of automated testing.

2019-02-21 18:06 UTC, daveconde commented
/lgtm

2019-02-21 18:07 UTC, daveconde commented
/approve

2019-02-21 18:07 UTC, daveconde approved these changes

2019-02-21 20:00 UTC, hferentschik requested changes

2019-02-21 20:00 UTC, hferentschik commented on CONTRIBUTING.md
> +## Filing issues
Looks like a double heading here

2019-02-21 20:00 UTC, hferentschik commented on CONTRIBUTING.md
> +# Contribution guidelines
Do we really need CONTRIBUTING for a internal testing app?

2019-02-21 20:00 UTC, hferentschik commented on charts/jx-app-test-lifecycle/Chart.yaml
> +description: A Helm chart for Kubernetes
We should start putting a proper description here.

2019-02-21 20:00 UTC, hferentschik commented on charts/jx-app-test-lifecycle/templates/rolebinding.yaml
> +  name: {{ template "fullname" . }}
Missing new line

2019-02-21 20:00 UTC, hferentschik commented on charts/jx-app-test-lifecycle/templates/serviceaccount.yaml
> +    heritage: {{ .Release.Service }}
Missing new line

2019-02-21 20:00 UTC, hferentschik commented on Jenkinsfile
> +          PREVIEW_VERSION = "0.0.0-SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER"
The preview variables are not needed

2019-02-21 20:00 UTC, hferentschik commented on charts/preview/Chart.yaml
> +description: A Helm chart for Kubernetes
No need for any of the _preview_ files. We neither build nor deploy a preview.

2019-02-21 20:00 UTC, hferentschik commented on charts/preview/values.yaml
> +    pullPolicy: IfNotPresent
newline

2019-02-21 20:00 UTC, hferentschik commented on go.sum
> +cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
that seems to be an awful long list, given the short list if dependencies. Have you tried to delete it and just running make to let go modules re-create it.

2019-02-21 20:00 UTC, hferentschik commented on charts/jx-app-test-lifecycle/Makefile
> +	git add --all
This is not working. This builds are not reproducible this way. The commit to master which the tag is referring to is never pushed. See also https://github.com/jenkins-x-apps/jx-app-jacoco/issues/68. It is working now in jx-app-jacoco.

2019-02-21 20:02 UTC, hferentschik commented
@daveconde - I don't think prow is integrated yet ;-) This requires an entry here https://github.com/jenkins-x/prow-config/blob/master/prow/config.yaml

2019-02-21 20:09 UTC, hferentschik reviewed
Seems there is no .gitignore

2019-02-21 20:21 UTC, deanesmith commented on Jenkinsfile
> +          PREVIEW_VERSION = "0.0.0-SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER"
Removed

2019-02-21 20:24 UTC, deanesmith commented on charts/jx-app-test-lifecycle/Chart.yaml
> +description: A Helm chart for Kubernetes
Done

2019-02-21 20:40 UTC, deanesmith commented on charts/preview/Chart.yaml
> +description: A Helm chart for Kubernetes
Done

2019-02-21 20:46 UTC, deanesmith commented on go.sum
> +cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
Yes.  Both of these files are fresh and I tried once again to be sure.

2019-02-23 01:21 UTC, deanesmith commented on charts/jx-app-test-lifecycle/Makefile
> +	git add --all
@hferentschik Will reach out to you regarding this.

2019-02-28 13:27 UTC, hferentschik commented on charts/jx-app-test-lifecycle/Makefile
> +	git add --all
I recommend we align with cb-app-sor.

2019-02-28 13:27 UTC, hferentschik commented on charts/jx-app-test-lifecycle/templates/service.yaml
> +kind: Service
No need really for a service

2019-02-28 13:28 UTC, hferentschik commented
@deanesmith have you pushed an update to this pull request already?

2019-03-18 20:18 UTC, hferentschik commented
/lgtm

2019-03-18 20:19 UTC, merged